# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-04-19 10:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('date_uploaded', models.DateField(verbose_name='Date Uploaded')),
                ('views', models.IntegerField(verbose_name='Views')),
                ('themes', models.ManyToManyField(to='video_app.Theme')),
            ],
            options={
                'ordering': ['title'],
                'verbose_name': 'Video',
                'verbose_name_plural': 'Videos',
            },
        ),
    ]
